default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= Rails.application.credentials[Rails.env.to_sym][:database_url] %>

test:
  <<: *default
  url: <%= Rails.application.credentials[Rails.env.to_sym][:database_url] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
